### ISSUE TITLE
How to ignore macOS require password when execute fastlane xcodes command?

### ISSUE THREAD

**Issue by haphanquang** [XcodesOrg/xcodes#269]
According to the documentation at https://docs.fastlane.tools/actions/xcodes/, I ran the command on Jenkins:
```
bundle exec fastlane run xcodes version:14.2.0
```
However, my build got stuck. I suspect it's asking for the macOS password, but there is no input interface in the Jenkins pipeline. 
I have already installed two Xcodes on the Jenkins machine, version 13.4.0 and 14.2.0, with the default Xcode being version 13.4.0. I would like to use Xcode 14.2.0 for building a specific branch.

**Comment by cmdrsabre** [comment]
as soon as I add an xcodes(version: "...") in my Fastfile and the selected version is not matching this, the gitlab-runner get's stuck with
`$ /opt/homebrew/bin/xcodes install '14.2' --update --select`
and I assume this is also because this commands asks for a password, although the runner has super user privileges!

**Comment by haphanquang** [comment]
I'm still facing this issue. I switched to Gitlab CI and run builds via shell runner. Cannot pass `xcodes` lane.

**Comment by VasileiosDiamantidis** [comment]
Hi @haphanquang  if you already installed the Xcode on Jenkins you can use the `select_for_current_build_only` parameter to `true`. Based on the [documentation](https://docs.fastlane.tools/actions/xcodes/) "does not change the global Xcode version, which would require sudo permissions — when this option is `true`, this action doesn't require sudo permissions"

**Comment by haphanquang** [comment]
Thanks @VasileiosDiamantidis you're saver.
