### ISSUE TITLE
Add --ignore-runtimes option

### ISSUE THREAD

**Issue by scientificworld** [XcodesOrg/xcodes#288]
Xcode requires a lot of disk space to install, while most of the contents are SDKs and emulators for each platform. But sometimes we just need part of them (e.g. you are only doing iOS development, so you don't need TVOS related SDKs and emulators).

So I think we can implement a `--ignore-runtimes` option, to remove these contents while installing Xcode.

**Comment by MattKiazyk** [comment]
@scientificworld going to close this issue as with Xcode 15, Apple has split out the SDK's to their own separate download for us :)
