### ISSUE TITLE
`--use-fastlane-auth` not available for `xcodes runtimes`

### ISSUE THREAD

**Issue by marc-48k** [XcodesOrg/xcodes#292]
Option `--use-fastlane-auth` is available for `xcodes [ download | install ]` but not for `xcodes runtimes [ download | install ]`.

```shell
xcodes runtimes download 'iOS 16.0' --use-fastlane-auth  
Error: Unknown option '--use-fastlane-auth'
```
I'm happy to raise a PR for this.

**Comment by MattKiazyk** [comment]
Hey @marc-48k thanks for the issue.

Unless something has changed, downloading runtimes does not require Apple Auth so therefore it hasn't been added in. 

Now only if this was possible with regular xcode versions 🤷

**Comment by marc-48k** [comment]
Sorry, my bad...

> Now only if this was possible with regular xcode versions
If only!
