### ISSUE TITLE
Runtimes installation fails when using aria2

### ISSUE THREAD

**Issue by sebnoumea** [XcodesOrg/xcodes#305]
Hi,

I wanted to install Xcode 15.0 beta 3's runtimes but got this error :
```shell
➜  ~ xcodes runtimes install "iOS 17.0-beta3"

Downloading with aria2 (/opt/homebrew/bin/aria2c)

XcodesKit/Environment.swift:80: Precondition failed: Aria must be called on the main queue
[1]    1648 trace trap  xcodes runtimes install "iOS 17.0-beta3"
```

Any clue on how to make things work again ?

Thanks

**Comment by jonbrooks** [comment]
I'm also running into this error, simply trying `xcodes install "15.0 Beta 3"`

This was working fine for me as recently as last week. I've tried `xcodes` version `1.3.0` and `1.4.1` (and whatever version I was on before I ran into this).

**Comment by krv5vignesh** [comment]
Facing the same issue while running "xcodes install 15.0 Beta 6" on Sonoma

**Comment by MattKiazyk** [comment]
See https://github.com/XcodesOrg/xcodes/issues/313 for a resolution Thanks
