### ISSUE TITLE
Can it list "Simulator Runtime" and download it ?

### ISSUE THREAD

**Issue by dourgulf** [XcodesOrg/xcodes#323]
As we known, new Xcode from 15.0 "Simulator Runtime" was seperated, and can be download and install by "xcrun simctl runtime add", so, it necessary to support such functionality.

**Comment by Blackjacx** [comment]
I think the same it is very annoying to have such a powerhouse to download and install Xcode in record time and then have to wait 30 minutes for the iOS runtime to be installed…

**Comment by gaige** [comment]
Isn't this in xcodes since this summer when xcode 15 went into beta?  There is an `xcodes runtimes` subcommand that lists available runtimes and `download` and `install` subcommands that download and install respectively.  Or is there something else?

**Comment by Blackjacx** [comment]
Ahh good to know! The question was about the GUI. I think there it is not supported yet

**Comment by MattKiazyk** [comment]
Xcodes.app supports downloading runtimes now!
