### ISSUE TITLE
"Xcode.app" couldn't be moved because you don't have permission to access "Applications".

### ISSUE THREAD

**Issue by iCanHazSoftware** [XcodesOrg/xcodes#330]
Even after installing the "Helper" I get this error on first Xcode install attempt.

**Comment by jordwms** [comment]
I'm having a similar problem. I get this error prompt when clicking "Make active" on an installed Xcode version. In this scenario the popup window heading is "Unable to create symbolic link".

**Comment by MattKiazyk** [comment]
This is the CLI repo, which looks like this issue is part of https://github.com/XcodesOrg/XcodesApp. Could you please create an issue there.
