### ISSUE TITLE
Unable to install helper

### ISSUE THREAD

**Issue by orzklv** [XcodesOrg/xcodes#331]
The operation couldn’t be completed. (CFErrorDomainLaunchd.4)

I'd gladly show logs if Xcodes does log anywhere, but idk where is it.

![image](https://github.com/XcodesOrg/xcodes/assets/54666588/0668a11c-f494-4a66-8824-cba10adc1d71)

**Comment by cyberclectic** [comment]
+1

**Comment by tinder-cfuller** [comment]
The log message can be found in Console.app, however the data appears to be obfuscated:

```
error	11:44:21.110841-0800	Xcodes	<private>: <private>
```

**Comment by tinder-cfuller** [comment]
I also encountered this issue.

The log message can be found in Console.app, however the data appears to be obfuscated:

```
error	11:44:21.110841-0800	Xcodes	<private>: <private>
```

**Comment by tinder-cfuller** [comment]
Relevant issue on the macOS app repository: https://github.com/XcodesOrg/XcodesApp/issues/485

**Comment by MattKiazyk** [comment]
This is the cli repo so closing!
