### ISSUE TITLE
Install Helper - The operation couldn’t be completed. (CFErrorDomainLaunchd.4)

### ISSUE THREAD

**Issue by atacan** [XcodesOrg/xcodes#332]
macOS 14.2.1 (23C71)
Xcodes 2.0.0 (20)

after the update I can't complete the installation of Xcode, because I can't install the helper. The helper installation error is in the title.

**Comment by MattKiazyk** [comment]
Please use the https://github.com/XcodesOrg/XcodesApp repo for Xcodes ui related issues
