### ISSUE TITLE
`xcodes runtime install` no longer working

### ISSUE THREAD

**Issue by NachoSoto** [XcodesOrg/xcodes#333]
Looks like Apple must have changed something, this has stopped working today:
```bash
$ sudo xcodes runtimes install "iOS 14.5" 
```

Leads to 
> Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not a valid property list.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Cannot parse a NULL or zero-length data" UserInfo={NSDebugDescription=Cannot parse a NULL or zero-length data})))

**Comment by adamsousa** [comment]
Same issue here, I'm not able to install anything using Xcode or xcodes. Seems like an Apple issue...

**Comment by NachoSoto** [comment]
You're right. Looks like the response is just empty:
```bash
curl 'https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex' \
-H 'Host: devimages-cdn.apple.com' \
-H 'If-None-Match: "3fe4f8deaace328312f2cad8b2a9c94c"' \
-H 'Accept: */*' \
-H 'If-Modified-Since: Thu, 25 Jan 2024 18:10:28 GMT' \
-H 'User-Agent: Xcode/22503 CFNetwork/1490.0.4 Darwin/23.2.0' \
-H 'Accept-Language: en-US,en;q=0.9' \
-H 'Connection: keep-alive'
```

```
HTTP/1.1 200 OK
x-amz-id-2: Ku2mQimK/rbp7nHSZ3peG2che7wpEJDZILMZceHZYRpn8gepGAoOEd8LmGVCsYj52N29sHBY8u4=
x-amz-request-id: CT0NCY3AF6HZF1XB
Date: Tue, 30 Jan 2024 22:09:37 GMT
Last-Modified: Tue, 30 Jan 2024 04:31:41 GMT
x-amz-server-side-encryption: AES256
x-amz-version-id: cDhwQHOubjWo0RD0wneYxK6zartyiYd9
Accept-Ranges: bytes
Content-Type: text/plain
Server: AmazonS3
Content-Length: 0
Cache-Control: max-age=600, public
Via: http/1.1 ussjc9-edge-lx-002.ts.apple.com (acdn/133.14417), http/1.1 ussjc9-edge-bx-007.ts.apple.com (acdn/224.14428)
X-Cache: hit-fresh, hit-fresh
CDNUUID: feb4cca2-be85-4bf4-95fd-5005d4b7260a-3017373680
Access-Control-Allow-Origin: *
Etag: "d41d8cd98f00b204e9800998ecf8427e"
Age: 422
Connection: keep-alive
```

**Comment by MattKiazyk** [comment]
I'll keep an eye on it. Hopefully they don't change the url.

**Comment by MattKiazyk** [comment]
@NachoSoto @adamsousa  Looks to be back up now.

**Comment by Jinxiansen** [comment]
It's the same issue? 
I can get other versions of 16 through this command, but iOS 15.5 version cannot be installed.

```
sudo xcodes runtimes install "iOS 15.5"

Found existing Runtime that will be used, at /Users/username/Downloads/com.apple.pkg.iPhoneSimulatorSDK15_5-15.5.1.1653527639.dmg.
Mounting DMG
Error: Failed executing: `/usr/bin/hdiutil attach -nobrowse -plist /Users/username/Downloads/com.apple.pkg.iPhoneSimulatorSDK15_5-15.5.1.1653527639.dmg` (1).
username ~ % /usr/bin/hdiutil attach -nobrowse -plist /Users/mobile-infra/Downloads/com.apple.pkg.iPhoneSimulatorSDK15_5-15.5.1.1653527639.dmg
hdiutil: attach failed - image not recognized

```

> https://devimages-cdn.apple.com/downloads/xcode/simulators/com.apple.pkg.iPhoneSimulatorSDK15_5-15.5.1.1653527639.dmg

<img width="826" alt="image" src="https://github.com/XcodesOrg/xcodes/assets/16829428/e3930e94-3ea1-4703-9933-362151099c0f">

**Comment by Jinxiansen** [comment]
@MattKiazyk 
Hi bro, dou you have any idea for above issue?

**Comment by NachoSoto** [comment]
Yeah 12 through 15 are failing with this:
```
Downloading Runtime iOS 12.4: 100%
Mounting DMG
Error: Failed executing: `/usr/bin/hdiutil attach -nobrowse -plist /Users/distiller/Downloads/com.apple.pkg.iPhoneSimulatorSDK12_4-12.4.1.1568665771.dmg` (1).
```

**Comment by MattKiazyk** [comment]
Anything below iOS 16, please use the old way via Xcode to install new simulators/runtimes or try to install manually.

**Comment by NachoSoto** [comment]
> The old way via Xcode

We use this from CI. Are you saying you don't plan to support this moving forward now that Apple seemingly broke it?

**Comment by daniel-beard** [comment]
@MattKiazyk that's not a viable option, since it's broken in Xcode for these versions as well. We'll just have to wait out this being fixed on Apple's side.

**Comment by MattKiazyk** [comment]
> Yeah 12 through 15 are failing with this:
> 
> ```
> Downloading Runtime iOS 12.4: 100%
> Mounting DMG
> Error: Failed executing: `/usr/bin/hdiutil attach -nobrowse -plist /Users/distiller/Downloads/com.apple.pkg.iPhoneSimulatorSDK12_4-12.4.1.1568665771.dmg` (1).
> ```

Sorry, after looking more, looks like those url's are returning zero bytes still! Who knows if Apple will fix those? 

My other comment was around that if you're wanting a specific runtime version, install that xcode version when it was baked in. That wont' work for all, but it might get you by?

**Comment by daniel-beard** [comment]
Looks to be resolved now

**Comment by MattKiazyk** [comment]
Glad to hear that @daniel-beard! Closing issue!

**Comment by NachoSoto** [comment]
Looks like iOS 12 and 13 are broken again lol

**Comment by MattKiazyk** [comment]
Looks like it's broken for all runtimes because the `seedNumber` value is sometimes an integer and sometimes a string now. 

```
<dict>
                <key>buildUpdate</key>
                <string>21E5184i</string>
                <key>platform</key>
                <string>com.apple.platform.iphoneos</string>
                <key>seedNumber</key>
                <integer>1</integer>
            </dict>
            <dict>
                <key>buildUpdate</key>
                <string>23E5180g</string>
                <key>platform</key>
                <string>com.apple.platform.macosx</string>
                <key>seedNumber</key>
                <integer>1</integer>
            </dict>
            <dict>
                <key>buildUpdate</key>
                <string>21E5195d</string>
                <key>platform</key>
                <string>com.apple.platform.iphoneos</string>
                <key>seedNumber</key>
                <string>2</string>
            </dict>
            <dict>
                <key>buildUpdate</key>
                <string>21T5196c</string>
                <key>platform</key>
                <string>com.apple.platform.watchos</string>
                <key>seedNumber</key>
                <string>2</string>
            </dict>
            <dict>
                <key>buildUpdate</key>
                <string>21L5206e</string>
                <key>platform</key>
                <string>com.apple.platform.appletvos</string>
                <key>seedNumber</key>
                <string>2</string>
            </dict>
            ```

**Comment by LeFatesmith** [comment]
The above is directly from: https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex

**Comment by MattKiazyk** [comment]
LOL. They've fixed it @NachoSoto

**Comment by NachoSoto** [comment]
Until they break it again in a few days lol
