### ISSUE TITLE
`xcodes runtimes install` fails with `Error: typeMismatch(Swift.Int, Swift.DecodingError.Context`

### ISSUE THREAD

**Issue by tachtevrenidis** [XcodesOrg/xcodes#334]
I know there was an issue last week with this but seems like it fixed itself. We now see another issue with:

```xcodes runtimes install "iOS 16.4"```

Error: typeMismatch(Swift.Int, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "sdkToSeedMappings", intValue: nil), _PlistKey(stringValue: "Index 110", intValue: 110), CodingKeys(stringValue: "seedNumber", intValue: nil)], debugDescription: "Expected to decode Int but found a string/data instead.", underlyingError: nil))

**Comment by MattKiazyk** [comment]
Going to close this in favour of keeping this open https://github.com/XcodesOrg/xcodes/issues/333#issuecomment-1930621099 

Apple changed their index, so hopefully they'll fix.. otherwise, we'll have to handle the change.

**Comment by tachtevrenidis** [comment]
thank you @MattKiazyk
