### ISSUE TITLE
Runtimes download Broken

### ISSUE THREAD

**Issue by MattKiazyk** [XcodesOrg/xcodes#368]
Since Xcode 16 updates things are broken.

new ContentType: `CryptexDiskImage` that isn't handled. 

```
<dict>
			<key>category</key>
			<string>simulator</string>
			<key>contentType</key>
			<string>cryptexDiskImage</string>
			<key>dictionaryVersion</key>
			<integer>2</integer>
			<key>downloadMethod</key>
			<string>mobileAsset</string>
			<key>fileSize</key>
			<integer>8455760175</integer>
			<key>identifier</key>
			<string>com.apple.dmg.iPhoneSimulatorSDK18_0_b1</string>
			<key>name</key>
			<string>iOS 18.0 beta Simulator Runtime</string>
			<key>platform</key>
			<string>com.apple.platform.iphoneos</string>
			<key>simulatorVersion</key>
			<dict>
				<key>buildUpdate</key>
				<string>22A5282m</string>
				<key>version</key>
				<string>18.0</string>
			</dict>
			<key>version</key>
			<string>18.0.0.1</string>
		</dict>
		```

**Comment by MattKiazyk** [comment]
> Just running `xcodes runtimes` fails here:
> 
> ```
> $ xcodes runtimes
> Error: keyNotFound(CodingKeys(stringValue: "source", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "downloadables", intValue: nil), _PlistKey(stringValue: "Index 114", intValue: 114)], debugDescription: "No value associated with key CodingKeys(stringValue: \"source\", intValue: nil) (\"source\").", underlyingError: nil))
> ```
> 
> This is on a Ventura machine with Xcode 15.0.1. Was working last month.

Looks like for the iOS 18 runtimes - there's no more `source` property that gave the URL to download it 😬

**Comment by phantomato** [comment]
Looks like it's still available at https://download.developer.apple.com/Developer_Tools/iOS_18_beta_Simulator_Runtime/iOS_18_beta_Simulator_Runtime.dmg which has a similar URL structure as the older versions.

Maybe we can infer the URL in case it's not present in the response?

**Comment by MattKiazyk** [comment]
> Maybe we can infer the URL in case it's not present in the response?

On: https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes it indicates that at some point the runtimes will be removed from there.

In investigating, I've found a few things.

Apple is using an apple archive now for simulators. People who are smarter then me hopefully can figure it out how we can download and extract the new form

<img width="595" alt="Screenshot 2024-06-10 at 10 11 16 PM" src="https://github.com/XcodesOrg/xcodes/assets/1119565/abba9788-11b0-4a5c-b436-7cc796cbd162">

**Comment by setoelkahfi** [comment]
I just got this when trying out Xcode 16 Beta.

**Comment by Ernest0-Production** [comment]
@MattKiazyk I think it makes sense to add softer processing for decoding each DownloadableRuntime object.

Currently, only the new SDKs do not have the source field, but the old ones do.

```swift
struct DownloadableRuntimesResponse: Decodable {
    let sdkToSimulatorMappings: [SDKToSimulatorMapping]
    let sdkToSeedMappings: [SDKToSeedMapping]
    let refreshInterval: Int
    @SaveArray var downloadables: [DownloadableRuntime]
    let version: String
}

```

**Comment by ObjectiveCesar** [comment]
> @MattKiazyk I think it makes sense to add safer decoding each DownloadableRuntime object.
> 
> Currently, only the new SDKs do not have the source field, but the old ones do.
> 
> ```swift
> struct DownloadableRuntimesResponse: Decodable {
>     let sdkToSimulatorMappings: [SDKToSimulatorMapping]
>     let sdkToSeedMappings: [SDKToSeedMapping]
>     let refreshInterval: Int
>     @SaveArray var downloadables: [DownloadableRuntime] // filters invalid array elements
>     let version: String
> }
> ```
> 
> I can help contribute this functionality.

That would be very much appreciated!

**Comment by MattKiazyk** [comment]
@Ernest0-Production yes that's the plan. At least allow old runtimes download and give proper errors for new ones. There's a branch started already which has this change. Was just investigating if I could do anything with it easily

**Comment by chramos** [comment]
same issue here

**Comment by Duduzera1997** [comment]
+1

**Comment by rhsalas3** [comment]
+1 

Specifically, trying to install the `16.4` runtime

**Comment by dourgulf** [comment]
when contentType is `cryptexDiskImage`, `source` field will missed
So, `enum ContentType` should add `cryptexDiskImage` case. and source should change type from `String` to `String?`

**Comment by phantomato** [comment]
Hi folks, I've made a simple workaround in my fork that supports installations of older + newer runtimes https://github.com/phantomato/xcodes/releases/tag/1.4.2

At the moment I'm able to install all the runtimes including iOS 18, VisionOS 2, watchOS 11. It works by assuming that the matching non-cryptex disk image still exists at https://developer.apple.com/download/all/ and consistently follows the naming convention. Hopefully, this will last long enough until we figure out the proper way to handle cryptex disk images.

Can be tried out using `brew install phantomato/patched/xcodes`

**Comment by chramos** [comment]
> Hi folks, I've made a simple workaround in my fork that supports installations of older + newer runtimes https://github.com/phantomato/xcodes/releases/tag/1.4.2
> 
> At the moment I'm able to install all the runtimes including iOS 18, VisionOS 2, watchOS 11. It works by assuming that the matching non-cryptex disk image still exists at https://developer.apple.com/download/all/ and consistently follows the naming convention. Hopefully, this will last long enough until we figure out the proper way to handle cryptex disk images.
> 
> Can be tried out using `brew install phantomato/patched/xcodes`

@phantomato  I cannot install your package.

this is the error I'm receiving when I try to install it:

```
Last 15 lines from /Users/ec2-user/Library/Logs/Homebrew/xcodes/01.make:

unsupported argument 'westmere' to option '-march='
clang: error: unsupported argument 'westmere' to option '-march='

unsupported argument 'westmere' to option '-march='
clang: error: unsupported argument 'westmere' to option '-march='

unsupported argument 'westmere' to option '-march='
clang: error: unsupported argument 'westmere' to option '-march='

unsupported argument 'westmere' to option '-march='
clang: error: unsupported argument 'westmere' to option '-march='

Build cancelled
make: *** [xcodes] Error 1
```
not sure what is the issue, but I have NO issues when I install the `xcodes` package with brew install xcodes command

**Comment by LeFatesmith** [comment]
Apple has changed the api in breaking ways a few times now, can we get an optional flag to supply the index as a file so we can unblock ourselves?

**Comment by testableapple** [comment]
Hi team, this issue is open for two weeks and, unfortunately, is a blocker for many of us. Do you have any ETA when it could be fixed for older runtimes? Thanks a million.

**Comment by LeFatesmith** [comment]
> Hi team, this issue is open for two weeks and, unfortunately, is a blocker for many of us. Do you have any ETA when it could be fixed for older runtimes? Thanks a million.

Agreed, using xcodes in our CI/CD environment is blocked every time Apple changes their API, even with all binaries cached.

**Comment by nichtverstehen** [comment]
We are maintaining public macOS GitHub runners and over time found that we just can't rely on downloading the runtime installers directly from Apple.

Instead of using the xcodes tool we maintain a few scripts to install Xcode and runtimes from existing packages. I published them here in case they would be useful to anyone here:

https://github.com/namespacelabs/xcode-install

**Comment by jayshah123** [comment]
Using official step from official docs `xcodebuild -downloadPlatform iOS` https://developer.apple.com/documentation/xcode/installing-additional-simulator-runtimes#Install-and-manage-Simulator-runtimes-from-the-command-line seems to work I guess? Is it recommended?

**Comment by testableapple** [comment]
It's unfortunate that this issue has been open for quite so long. I decided to switch to [ipsw](https://github.com/blacktop/ipsw).

Think this might help someone:
```bash
echo 'iOS 16.4 Simulator' | ipsw download xcode --sim
```

**Comment by MattKiazyk** [comment]
Thanks for your patience. 1.5.0 has been released which fixes the old runtime downloads.

**Comment by uknowmeright** [comment]
This seemed to have fixed itself for us for about a month but now the same issue is happening consistently. 

`Run xcodes runtimes install --keep-archive 'iOS 16.1'
  xcodes runtimes install --keep-archive 'iOS 16.1'
  shell: /bin/bash -e {0}
  env:
    GITHUB_RUN_URL: xxxx
    MD_APPLE_SDK_ROOT: /Applications/Xcode_15.4.app
Error: Failed executing: `/usr/bin/xcrun simctl runtime add /Users/runner/Downloads/iOS_16.1_Simulator_Runtime.dmg` (1[4]
Installing Runtime
Error: Process completed with exit code 1.`

Is this still failing for anyone else?

**Comment by testableapple** [comment]
@uknowmeright, I faced the same problem on GitHub Actions. It seems like they recently (literally last week) reduced the size of available disk space, so you can't download/mount an additional iOS Runtime.

I solved this by removing the existing simulators before installing the required runtime, e.g.:
```bash
- name: Download 16.4 sim
  run: |
    sudo rm -rfv ~/Library/Developer/CoreSimulator/* || true
    sudo xcodes runtimes install --keep-archive 'iOS 16.4'
```

In other words, now you just need to free some space before downloading the runtimes on GitHub Actions. Hope this helps.

**Comment by alvar-bolt** [comment]
For people who visit this thread in search of ways to download iOS 18 simulators.

Xcode 16.1 Beta 3 added support for downloading specific simulators:

> Xcodebuild’s download platforms command now supports an optional -buildVersion argument to request a specific released simulator runtime. The can be a build update number or the release number. Simulator runtime version that are supported versions are iOS 16.0+, watchOS 9.0+, tvOS 16+, visionOS 1.0+.
> 
> Example usage, to download, install and export the iOS 16.0 simulator runtime:
> 
> xcodebuild -downloadPlatform iOS -buildVersion 16.0 -exportPath ./SimRuntimeImages/ xcodebuild -downloadPlatform iOS -buildVersion 20A360 -exportPath ./SimRuntimeImages/ (135989441) (FB15126412)
