### ISSUE TITLE
DownloadableRuntime decode error

### ISSUE THREAD

**Issue by hasayakey** [XcodesOrg/xcodes#374]
https://devimages-cdn.apple.com/downloads/xcode/simulators/index2.dvtdownloadableindex
![screenshot-1719208818935](https://github.com/XcodesOrg/xcodes/assets/12247200/84e4143f-48cd-4ef5-b22b-b1c9fadaffd0)

**Comment by MattKiazyk** [comment]
1.5.0 has been released. Downloading of iOS 18 runtimes are not supported but you should be able to use the tool. Thanks
