### ISSUE TITLE
`xcodes runtimes` throws error

### ISSUE THREAD

**Issue by Blackjacx** [XcodesOrg/xcodes#377]
WHen I execute the command above to retrieve (installed) runtimes I get the following error:

```swift
xcodes runtimes
Error: keyNotFound(CodingKeys(stringValue: "source", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "downloadables", intValue: nil), _PlistKey(stringValue: "Index 114", intValue: 114)], debugDescription: "No value associated with key CodingKeys(stringValue: \"source\", intValue: nil) (\"source\").", underlyingError: nil))
```

Maybe this is related to https://github.com/XcodesOrg/xcodes/issues/363 🤔

**Comment by DargonLee** [comment]
same issue here 
![image](https://github.com/user-attachments/assets/33dfc354-4518-4025-aa39-fe6c63001af4)

**Comment by MattKiazyk** [comment]
this is fixed in all latest releases
