### ISSUE TITLE
Which Homebrew tap to use

### ISSUE THREAD

**Issue by bartekpacia** [XcodesOrg/xcodes#379]
There's both [`xcodes` formula](https://formulae.brew.sh/formula/xcodes) and [`xcodes` cask](https://formulae.brew.sh/cask/xcodes) in Homebrew core.

But then there's also this tap: https://github.com/XcodesOrg/homebrew-made and there's only the `xcodes` formula inside.

Which one should I use? 

PS Thanks for all the hard work! This project is awesome.

**Comment by andrewcrook** [comment]
>  There's both [xcodes formula](https://formulae.brew.sh/formula/xcodes) and [xcodes cask](https://formulae.brew.sh/cask/xcodes) in Homebrew core.

Hi @bartekpacia 

`brew install  --formula xcodes # = xcodes commanline `
`brew install  --casks xcodes # = xcodesapp which is GUI based and a separate repo`

> But then there's also this tap: https://github.com/XcodesOrg/homebrew-made and there's only the xcodes formula inside.

comparing with homebrew core formula and casks and this repo

The repo '/XcodesOrg/homebrew-cask‘ is a fork  of homebrew core not a tap it was probably used to create a pull request to merge back into homebrew core, that is, it was used submit the formula (command line version) to homebrew.  

'/XcodesOrg/homebrew-made’  is also the xcodes formula (command line) it uses the release binary from the repos release page where homebrew core has compiled versions for each major version of macOS also they are not universal binaries so you have separate intel and arm64 versions.  I cannot tell in this circumstance, its different for each package,  but it **could** mean smaller and optimised binaries.  These were all compiled autonomously via homebrew maintenance team.

> Which one should I use?

If its available on homebrew I would recommend  everyone uses homebrew .. its what its there for.
Unless there are some specific reasons not to, then you use a tap, this can be for commercial software, software that relies on commercial software, specialised software, old and  depreciated software and removed from homebrew.
