### ISSUE TITLE
when try install xcode 16 it is showing me error on step 2

### ISSUE THREAD

**Issue by mrpower55** [XcodesOrg/xcodes#386]
i have download xcode 16 and when try to extract it on step 2 it is showing me

The operation couldn’t be completed. (ProcessExecutionError(process: <NSConcreteTask: 0x600001a29900>, standardOutput: "xip: signing certificate was \"Software Update\" (validation not attempted)\n", standardError: "xip: error: The archive “Xcode-16.0.0+16A242d.xip” failed to be moved to the final destination due to the error: The operation couldn’t be completed. Operation not permitted.\n"))

hope it can solved soon, thanks

**Comment by willwfsp** [comment]
Same here

**Comment by 99arobe** [comment]
I too had this error until I enabled full disk access (System Preferences >  Privacy & Security > Full Disk Access) on my mac for my terminal (Warp)
