### ISSUE TITLE
AppleID not recognized; Invalid JSON

### ISSUE THREAD

**Issue by kct3937** [XcodesOrg/xcodes#388]
Suddenly XCodes has an error reading my Account info. Worked yesterday, but this morning...hooped!
Checked my AppleID and all is good.
No Change in the information at all.
Looks like XCodes did an update during the night
Version: 2.3.0

![CleanShot 2024-10-19 at 12 18 02](https://github.com/user-attachments/assets/a1fccd37-5e8f-47ed-a24f-6b4455ad5eba)

**Comment by bohdanpodvirnyi** [comment]
same issue here

**Comment by ElvisFeagin** [comment]
Same problem. Running latest version. Cannot Sign in. Checked userid/password. These are correct.
<img width="619" alt="Screenshot 2024-10-20 at 6 53 18 AM" src="https://github.com/user-attachments/assets/6903faca-50c7-43de-922d-3f3103930acb">

**Comment by sethbang** [comment]
+1

Terminal:

xcodes install --latest-prerelease
Updating...
Latest prerelease version available is 16.1 Beta 3
Apple ID: xxxx
Apple ID Password: xxxx

The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '<' around line 1, column 1." UserInfo={NSJSONSerializationErrorIndex=0, NSDebugDescription=Unexpected character '<' around line 1, column 1.}))))

The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '<' around line 1, column 1." UserInfo={NSJSONSerializationErrorIndex=0, NSDebugDescription=Unexpected character '<' around line 1, column 1.}))))

**Comment by MattKiazyk** [comment]
Hey everybody. Apple removed the way Apple sessions are done so I need to updates both Xcodes to handle the new way. This affected fast lane and others as well. 

Please be patient. I'll be doing my best to update and release a fix this week. 

https://github.com/XcodesOrg/XcodesApp/issues/630 for same issue in Xcodes UI

Thanks
-Matt

**Comment by spadafiva** [comment]
Sorry for the spam, but will this also resolve the issue with the [iOS 18 runtimes here](https://github.com/XcodesOrg/xcodes/issues/384#issuecomment-2380878485) or are they unrelated?

**Comment by MattKiazyk** [comment]
@spadafiva for clarification, the issue you are linking is not related. I added iOS 18 runtime downloads to the Xcodes UI, and was starting to add it into the CLI, when the login issue stopped that. Downloading of runtimes does not require any logins.

**Comment by kct3937** [comment]
Ok, thanks for the clarification.

**Comment by spadafiva** [comment]
> @spadafiva for clarification, the issue you are linking is not related. I added iOS 18 runtime downloads to the Xcodes UI, and was starting to add it into the CLI, when the login issue stopped that. Downloading of runtimes does not require any logins. 
> 
> 

Is there anything I could do to help with this or translate from the xcodes app into this tool?

**Comment by MattKiazyk** [comment]
> > @spadafiva for clarification, the issue you are linking is not related. I added iOS 18 runtime downloads to the Xcodes UI, and was starting to add it into the CLI, when the login issue stopped that. Downloading of runtimes does not require any logins.
> 
> Is there anything I could do to help with this or translate from the xcodes app into this tool?

The UI PR is here: https://github.com/XcodesOrg/XcodesApp/pull/622 for reference. It needs Xcode 16.1 Beta 3+ as it uses its `xcodebuild` command to download the runtime.

**Comment by spadafiva** [comment]
> The UI PR is here: [XcodesOrg/XcodesApp#622](https://github.com/XcodesOrg/XcodesApp/pull/622) for reference. It needs Xcode 16.1 Beta 3+ as it uses its `xcodebuild` command to download the runtime.

Awesome, thank you!  To clarify, do you know if the 16.1 release candidate also has this change or if it's something particular to that beta?

**Comment by MattKiazyk** [comment]
> > The UI PR is here: [XcodesOrg/XcodesApp#622](https://github.com/XcodesOrg/XcodesApp/pull/622) for reference. It needs Xcode 16.1 Beta 3+ as it uses its `xcodebuild` command to download the runtime.
> 
> Awesome, thank you! To clarify, do you know if the 16.1 release candidate also has this change or if it's something particular to that beta?

I see it just got released - I haven't tested it, but assuming that anything starting with beta 3 has it going forward. So RC1 should be fine. The user just has to have that Xcode selected/active.

**Comment by MattKiazyk** [comment]
18.0 runtime downloads are not supported (yet) by the CLI. This repo is for the CLI, not the UI.

**Comment by jeffypooo** [comment]
I am also seeing similar JSON decode errors now with 1.5.0

**Comment by PetterBraka-Trainline** [comment]
I have the same issue

**Comment by KyleARector** [comment]
I also have the issue

**Comment by calebhearth** [comment]
Y'all we've been asked to stop +1ing this. If you're trying to follow along there's a notifications picker on the right hand side of this page on desktop.

**Comment by PetterBraka-Trainline** [comment]
Fastlane had the same issue. It was caused by "Apple started using their own variant of SRP (Secure Remote Password) using SHA-256 and 2048 bit hashing in the sign in flow."
https://github.com/fastlane/fastlane/issues/26368#issuecomment-2435770145

**Comment by khambley** [comment]
Just installed and having same issue

**Comment by MattKiazyk** [comment]
v 1.6.0 is now available to install with support for the SRP Login

**NOTE: If you are still having trouble with invalid username/password being returned - people have been having success resetting their password via https://account.apple.com/.**

**Comment by kct3937** [comment]
Awesome, thanks for the update!

Thank you for the good work.  It's working as well as before

**Comment by kct3937** [comment]
Already done.
