### ISSUE TITLE
Install not prompting for apple id login?

### ISSUE THREAD

**Issue by gimulnautti** [XcodesOrg/xcodes#392]
Instead of asking for apple ID login, xcodes install 15.4 just fails with the following error:

The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0}))))
The operation couldn’t be completed. (DecodingError.dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around line 1, column 0." UserInfo={NSDebugDescription=Invalid value around line 1, column 0., NSJSONSerializationErrorIndex=0}))))

**Comment by gimulnautti** [comment]
install from path, with .xip downloaded works normally

**Comment by MSchmidt** [comment]
Probably the same as this: https://github.com/XcodesOrg/xcodes/issues/388#issuecomment-2425082727

**Comment by MattKiazyk** [comment]
Please follow #388 Fix coming soon
